config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get "/search", to: "searchs#search"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :bookcomments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :followers, on: :member
    get :followeds, on: :member
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :relationships, foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :relationships, source: :followed

  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: :followed_id, dependent: :destroy
  has_many :followeds, through: :reverse_of_relationships, source: :follower

  def is_followed_by?(user)
    reverse_of_relationships.find_by(follower_id: user.id).present?
  end



  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update]

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @two_days_ago = @books.created_two_days_ago
    @three_days_ago = @books.created_three_days_ago
    @four_days_ago = @books.created_four_days_ago
    @five_days_ago = @books.created_five_days_ago
    @six_days_ago = @books.created_six_days_ago
    @this_week = @books.created_this_week
    @last_week = @books.created_last_week

  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  def followeds
    user = User.find(params[:id])
    @users = user.followeds
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_count.html.erb
<div class = "table_width">
  <caption>7日分の投稿数</caption>
   <table class="table table-bordered">
    <thead>
     <tr>
      <th>6日前</th>
      <th>5日前</th>
      <th>4日前</th>
      <th>3日前</th>
      <th>2日前</th>
      <th>1日前</th>
      <th>今日</th>
     </tr>
    </thead>
    <tbody>
     <tr>
     　<td><%= @today_book.count %></td>
     　<td><%= @yesterday_book.count %></td>
     　<td><%= @two_days_ago.count %></td>
     　<td><%= @three_days_ago.count %></td>
     　<td><%= @four_days_ago.count %></td>
     　<td><%= @five_days_ago.count %></td>
     　<td><%= @six_days_ago.count %></td>
     </tr>
    </tbody>
   </table>
  </div>

app/views/users/_follow.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(50,50) %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.followers.count %></td>
        <td>フォロワー数:<%= user.followeds.count %></td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(50,50) %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.followers.count %></td>
        <td>フォロワー数:<%= user.followeds.count %></td>
        <% if user.id != current_user.id %>
          <td>
            <% if user.is_followed_by?(current_user) %>
              <%= link_to user_relationships_path(user), method: :delete do %>
                <p>フォローを外す</p>
              <% end %>
            <% else %>
              <%= link_to user_relationships_path(user), method: :post do %>
                <p>フォローする</p>
              <% end %>
            <% end %>
          </td>
        <% else %>
          <td></td>
        <% end %>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image(100,100) %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followers.count, followers_user_path(user) %></th>
  </tr>
   <tr>
    <th>followers</th>
    <th><%= link_to user.followeds.count, followeds_user_path(user) %></th>
  </tr>
</table>

<div class='row'>
  <% if user.id == current_user.id %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followeds.html.erb
<h2>Follower User</h2>
<% if @users.present? %>
  <%= render 'follow', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/followers.html.erb
<h2>Follow User</h2>
<% if @users.present? %>
  <%= render 'follow', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
        <% if @user.id != current_user.id %>
          <% if @user.is_followed_by?(current_user) %>
            <%= link_to user_relationships_path(@user), method: :delete do %>
              <putton class="btn btn-danger">フォローを外す</putton>
            <% end %>
          <% else %>
            <%= link_to user_relationships_path(@user), method: :post do %>
              <putton class="btn btn-primary">フォロー</putton>
            <% end %>
          <% end %>
        <% end %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index', books: @books %>
      <%= render 'users/count' %>
      <%= render 'books/graph' %>

    </div>
  </div>
</div>