config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get "/search", to: "searchs#search"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :bookcomments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :followers, on: :member
    get :followeds, on: :member
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :bookcomments, dependent: :destroy

  scope :created_today, -> { where(created_at: Time.zone.now.all_day) } # 今日
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }# 前日
  scope :created_two_days_ago, -> { where(created_at: 2.day.ago.all_day) }
  scope :created_three_days_ago, -> { where(created_at: 3.day.ago.all_day) }
  scope :created_four_days_ago, -> { where(created_at: 4.day.ago.all_day) }
  scope :created_five_days_ago, -> { where(created_at: 5.day.ago.all_day) }
  scope :created_six_days_ago, -> { where(created_at: 6.day.ago.all_day) }

  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) } # 今週
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) } # 先週

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE ?', content + '%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%' + content)
    else
      Book.where('title LIKE ?', '%' + content + '%')
    end
  end

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  acts_as_taggable
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.new
    @books = Book.find(params[:id])
    @user = @books.user
    @book_comment = Bookcomment.new

  end

  def index
    @book = Book.new
    if params[:button].to_i == 1
      @books= Book.all.order(created_at: :desc)
    elsif params[:button].to_i == 2
      @books= Book.all.order(star: :desc)
    else
      @books = Book.all
      if params[:tag_name]
        @books = Book.tagged_with("#{params[:tag_name]}")
      end
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :star, :tag_list)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <p>Category<p>
    <%= f.text_field :tag_list, value: book.tag_list, class: 'form-control book_tag_list' %>
  </div>

  <% if book.id === nil %>
    <div class="form-group" id="star">
      <%= f.label :star,'Rate', class:'col-md-3 col-form-label' %>
      <%= f.hidden_field :star, id: :review_star %>
    </div>

    <!-- 評価javascript -->
    <script>
    $('#star').raty({
      size     : 36,
      starOff:  '<%= asset_path('star-off.png') %>',
      starOn : '<%= asset_path('star-on.png') %>',
      scoreName: 'book[star]',
      half: false,
    });
    </script>
  <% else %>
     <% render body: nil %>
  <% end %>

  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>

<% end %>

app/views/books/_graph.html.erb
<canvas id="myLineChart"></canvas>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>

  <script>
  const ctx = document.getElementById("myLineChart");
  const myLineChart = new Chart(ctx, {
    // グラフタイプを設定する項目
    type: 'line',

    // データをセットする項目
    data: {
      labels: ['6日前', '５日前', '４日前', '３日前', '２日前', '１日前', '今日'],
      datasets: [
        {
          label: '投稿した本の数',
          data:
          [<%=@six_days_ago.count %>,
          <%=@five_days_ago.count %> ,
          <%=@four_days_ago.count %>,
          <%=@three_days_ago.count %>,
          <%=@two_days_ago.count %>,
          <%=@yesterday_book.count %>,
          <%=@today_book.count %>
          ],
          borderColor: "blue",
          backgroundColor: "grey"
        },
      ],
    },

    // グラフのオプションをつける設定
    options: {
      title: {
        display: true,
        text: '７日間の本の投稿数'
      },
      scales: {
        yAxes: [{
          ticks: {
            suggestedMax: 10,
            suggestedMin: 0,
            stepSize: 1,
            callback: function(value, index, values){
              return  value
            }
          }
        }]
      },
    }
  });
  </script>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Category</th>
      <th></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.id) do %>
          <%= image_tag book.user.get_profile_image(50,50) %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td><%= render 'books/tag_list', tag_list: book.tag_list %></td>
        <td id="favorite_btn_<%= book.id %>">
          <%= render 'favorites/favorite', book: book %>
        </td>
        <td>
          <p>コメント数：<%= book.bookcomments.count %></p>
        </td>
        <td>
           <div id="star-rate<%= book.id%>"></div>
            <script>
              $('#star-rate<%= book.id%>').raty({
                size      : 36,
                starOff   : '<%= asset_path('star-off.png') %>',
                starOn    : '<%= asset_path('star-on.png') %>',
                half      : false,
                readOnly: true,
                score: <%= book.star %>,
              });
            </script>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_tag_list.html.erb
<% tag_list.each do |tag| %>
<%= link_to tag, books_path(tag_name: tag) %>
<% end %>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <%= render 'layouts/errors', obj: @book %>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= link_to "新しい順", {action: :index, button: 1} %> |
      <%= link_to "評価の高い順", {action: :index, button: 2} %>
      <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td>
            <%= link_to(@books.user) do %>
              <%= image_tag @books.user.get_profile_image(50,50) %><br>
              <%= @books.user.name %>
            <% end %>
          </td>
          <td>
            <%= link_to @books.title, @book %>
          </td>
          <td>
            <%= @books.body %>
          </td>
          <td><%= render 'books/tag_list', tag_list: @books.tag_list %></td>
          <td id="favorite_btn_<%= @books.id %>">
            <%= render 'favorites/favorite', book: @books %>
          </td>
          <td>
            <p>コメント数：<%= @books.bookcomments.count %></p>
          </td>

          <td>
            <div id="star-rate<%= @books.id%>"></div>
            <script>
              $('#star-rate<%= @books.id%>').raty({
                size      : 36,
                starOff   : '<%= asset_path('star-off.png') %>',
                starOn    : '<%= asset_path('star-on.png') %>',
                half      : false,
                readOnly: true,
                score: <%= @books.star %>,
              });
            </script>
          </td>

          <% if @books.user_id == current_user.id %>
            <td><%= link_to 'Edit', edit_book_path(@books), class: "btn btn-sm btn-success edit_book_#{@books.id}" %></td>
            <td><%= link_to 'Destroy', @books, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
        </tr>
      </table>

      <table class="book-comments">
        <%= render "bookcomments/comment", books: @books %>
      </table>

      <div>
        <%= render 'bookcomments/bookcomment', books: @books, book_comment: @book_comment %>
      </div>
  </div>
</div>